version: '2'

# app + docker in the same container
#services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    ports:
#      - "9999:1901"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=Lovely789123!
#      - SERVER.PORT=1901
##      - SPRING_JPA_HIBERNATE_DDL_AUTO=CREATE-DROP
#
#  db:
#    image: 'postgres:13.1-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=Lovely789123!
#      - DATABASE_HOST:db
#      - POSTGRES_DB=student

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "9999:1901"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/student
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Lovely789123!
      - SERVER.PORT=1901
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=CREATE-DROP
